name: Laravel Lint & Static Analysis

on:
  pull_request:
    branches:
      - develop
      - release/*
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v7

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Instalar dependencias
        run: composer install --no-interaction --prefer-dist

      - name: Ejecutar PHPStan
        run: ./vendor/bin/phpstan analyse --configuration=phpstan.neon.dist app/


      - name: Ejecutar PHPCS
        run: ./vendor/bin/phpcs --standard=PSR12 app/
