name: Release Changelog

on:
  push:
    tags:
      - 'v*.*.*'   # Se activa al hacer push de un tag como v0.0.1

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v7

      - name: Generar changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v5 # SHA de la acción
        with:
          configuration: ".github/changelog-config.json"

      - name: Crear Release en GitHub
        uses: softprops/action-gh-release@v2 # SHA de la acción
        with:
          body: ${{ steps.changelog.outputs.changelog }}
